import json
import re
import httpx
from abc import ABC, abstractmethod
from typing import List, Dict, Any, Optional

class ProviderResponse:
    def __init__(self, content: str = "", thought: str = "", tool_calls: Optional[List[dict]] = None):
        self.content = content
        self.thought = thought
        self.tool_calls = tool_calls or []

class BaseLLMProvider(ABC):
    @abstractmethod
    async def generate(
        self,
        messages: List[Dict[str, str]],
        tools_schema: Optional[List[dict]] = None,
        temperature: float = 0.7
    ) -> ProviderResponse:
        pass

class GeminiProvider(BaseLLMProvider):
    def __init__(self, api_key: str, model: str = "gemini-2.0-flash"):
        self.api_key = api_key
        self.model = model

    async def generate(
        self,
        messages: List[Dict[str, str]],
        tools_schema: Optional[List[dict]] = None,
        temperature: float = 0.7
    ) -> ProviderResponse:
        if not self.api_key:
            raise ValueError("Gemini API key is not configured.")

        url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model}:generateContent?key={self.api_key}"

        # Convert chat messages to Gemini contents format
        contents = []
        system_instruction = None
        for m in messages:
            if m["role"] == "system":
                if "Observation" in m.get("content", ""):
                    contents.append({
                        "role": "user",
                        "parts": [{"text": f"[Tool Observation]\n{m['content']}"}]
                    })
                else:
                    system_instruction = {"parts": [{"text": m["content"]}]}
            else:
                role = "user" if m["role"] == "user" else "model"
                contents.append({
                    "role": role,
                    "parts": [{"text": m["content"]}]
                })

        payload: Dict[str, Any] = {
            "contents": contents,
            "generationConfig": {"temperature": temperature}
        }
        if system_instruction:
            payload["systemInstruction"] = system_instruction

        # Convert tool schemas to Gemini function declarations if provided
        if tools_schema:
            function_declarations = []
            for t in tools_schema:
                function_declarations.append({
                    "name": t["name"],
                    "description": t["description"],
                    "parameters": t["parameters"]
                })
            payload["tools"] = [{"functionDeclarations": function_declarations}]

        async with httpx.AsyncClient(timeout=60.0) as client:
            resp = await client.post(url, json=payload)
            if resp.status_code != 200:
                raise RuntimeError(f"Gemini API Error ({resp.status_code}): {resp.text}")

            data = resp.json()
            candidates = data.get("candidates", [])
            if not candidates:
                return ProviderResponse(content="No response generated by Gemini.")

            candidate = candidates[0]
            parts = candidate.get("content", {}).get("parts", [])

            content_text = ""
            thought_text = ""
            tool_calls = []

            for part in parts:
                if "text" in part:
                    text_val = part["text"]
                    # Extract thinking tags if present (e.g. <thought>...</thought>)
                    thought_match = re.search(r"<thought>(.*?)</thought>", text_val, re.DOTALL)
                    if thought_match:
                        thought_text += thought_match.group(1).strip()
                        text_val = re.sub(r"<thought>.*?</thought>", "", text_val, flags=re.DOTALL).strip()
                    content_text += text_val
                elif "functionCall" in part:
                    fc = part["functionCall"]
                    tool_calls.append({
                        "name": fc.get("name"),
                        "args": fc.get("args", {})
                    })

            return ProviderResponse(content=content_text, thought=thought_text, tool_calls=tool_calls)

class OpenAIProvider(BaseLLMProvider):
    def __init__(self, api_key: str, model: str = "gpt-4o-mini", base_url: str = "https://api.openai.com/v1"):
        self.api_key = api_key
        self.model = model
        self.base_url = base_url.rstrip("/")

    async def generate(
        self,
        messages: List[Dict[str, str]],
        tools_schema: Optional[List[dict]] = None,
        temperature: float = 0.7
    ) -> ProviderResponse:
        if not self.api_key:
            raise ValueError("API key is not configured for OpenAI/Groq provider.")

        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json"
        }

        payload: Dict[str, Any] = {
            "model": self.model,
            "messages": messages,
            "temperature": temperature
        }

        if tools_schema:
            payload["tools"] = [{"type": "function", "function": t} for t in tools_schema]

        async with httpx.AsyncClient(timeout=60.0) as client:
            resp = await client.post(f"{self.base_url}/chat/completions", headers=headers, json=payload)
            if resp.status_code != 200:
                raise RuntimeError(f"OpenAI/Groq API Error ({resp.status_code}): {resp.text}")

            data = resp.json()
            choice = data["choices"][0]["message"]
            content = choice.get("content") or ""
            thought = ""
            tool_calls = []

            # Check if model has reasoning_content (DeepSeek / Groq R1)
            if "reasoning_content" in choice:
                thought = choice["reasoning_content"]

            if choice.get("tool_calls"):
                for tc in choice["tool_calls"]:
                    fn = tc.get("function", {})
                    args = {}
                    try:
                        args = json.loads(fn.get("arguments", "{}"))
                    except Exception:
                        pass
                    tool_calls.append({
                        "name": fn.get("name"),
                        "args": args
                    })

            return ProviderResponse(content=content, thought=thought, tool_calls=tool_calls)

class OllamaProvider(BaseLLMProvider):
    def __init__(self, base_url: str = "http://localhost:11434", model: str = "llama3"):
        self.base_url = base_url.rstrip("/")
        self.model = model

    async def generate(
        self,
        messages: List[Dict[str, str]],
        tools_schema: Optional[List[dict]] = None,
        temperature: float = 0.7
    ) -> ProviderResponse:
        url = f"{self.base_url}/api/chat"
        payload = {
            "model": self.model,
            "messages": messages,
            "stream": False,
            "options": {"temperature": temperature}
        }

        async with httpx.AsyncClient(timeout=60.0) as client:
            resp = await client.post(url, json=payload)
            if resp.status_code != 200:
                raise RuntimeError(f"Ollama Error ({resp.status_code}): {resp.text}")

            data = resp.json()
            msg = data.get("message", {})
            content = msg.get("content", "")
            return ProviderResponse(content=content)

from core.self_ai import SelfAIEngine

class SelfAIProvider(BaseLLMProvider):
    """
    100% Self-Contained, Autonomous AI Engine for Nexus-AI.
    Operates completely offline with zero external API calls, zero API keys, and zero telemetry.
    """
    def __init__(self, ollama_fallback: bool = True):
        self.ollama_fallback = ollama_fallback

    async def generate(
        self,
        messages: List[Dict[str, str]],
        tools_schema: Optional[List[dict]] = None,
        temperature: float = 0.7
    ) -> ProviderResponse:
        # Extract RAG context from system message if present
        system_msg = next((m.get("content", "") for m in messages if m.get("role") == "system"), "")
        rag_context = ""
        if "Relevant Knowledge Base Information:" in system_msg:
            rag_context = system_msg.split("Relevant Knowledge Base Information:")[-1]

        last_msg = messages[-1]["content"] if messages else ""

        # Check if local offline Ollama is running (optional local neural accelerator)
        has_obs = any("Observation" in m.get("content", "") for m in messages[-2:])
        if self.ollama_fallback and not has_obs:
            local_llm_result = await SelfAIEngine.try_local_ollama(messages)
            if local_llm_result:
                return ProviderResponse(
                    content=local_llm_result,
                    thought="Generated response using local offline Ollama neural weights (100% private, 0 APIs)."
                )

        # Process through native SelfAIEngine cognitive reasoning loop
        result = SelfAIEngine.process_query(last_msg, messages, rag_context=rag_context)
        return ProviderResponse(
            content=result.get("content", ""),
            thought=result.get("thought", ""),
            tool_calls=result.get("tool_calls", [])
        )

# Backward-compatibility alias
LocalFallbackProvider = SelfAIProvider

